# Generated by Django 2.1.7 on 2019-03-18 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EMailCompose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=60)),
                ('date_sented', models.DateTimeField(blank=True, null=True)),
                ('attach', models.FileField(default='default.csv', upload_to='email_file')),
                ('message', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='date_sented', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
