# Generated by Django 2.1.7 on 2019-03-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0002_auto_20190318_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcompose',
            name='bcc',
            field=models.EmailField(default=False, max_length=254),
        ),
        migrations.AddField(
            model_name='emailcompose',
            name='cc',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
