# Generated by Django 2.1.7 on 2019-03-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailapp', '0003_auto_20190319_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcompose',
            name='bcc',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailcompose',
            name='cc',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
